apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-default
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jumpbox-academy/argocd-levis
    targetRevision: main
    path: deployment/default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true