apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: levis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jumpbox-academy/argocd-levis
    targetRevision: main
    path: deployment/levis
    plugin:
      name: levis-argocd-plugin-v1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true